#!/usr/bin/env bash

shopt -s extglob
set -o errtrace
set -o errexit

echo "Phil's Server Bootstrapper"
echo "=========================="
echo "Please make sure that you have these packages installed:"
echo ">> git, cmake, make, vim, tmux, zsh, python-dev (for some distros)"
echo "\nAuto installation will start in 5 seconds."
sleep 5

DEFAULT_REPO="https://github.com/phil5/dotfiles.git"
DEFAULT_LOCATION=~/Developer
DEFAULT_REPO_NAME=dotfiles

mkdir -p $DEFAULT_LOCATION
cd $DEFAULT_LOCATION
if [ -d $DEFAULT_LOCATION/$DEFAULT_REPO_NAME ]; then
    cd $DEFAULT_LOCATION/$DEFAULT_REPO_NAME
    git pull
else
    git clone $DEFAULT_REPO
    cd $DEFAULT_REPO_NAME
fi

make modules
make gitconfig
make vim-fast
make tmux
make zsh

echo "You may want to manually switch to zsh by \`chsh -s zsh\`"
echo "Done."

